version: '3.8'

services:
  flask_app:
    build: 
      context: .
    image: flask_test:latest
    container_name: flask_app_container
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.main:create_app
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://admin:cksdud0927@database-1.ct008eu6g22u.ap-northeast-2.rds.amazonaws.com:3306/database-1
    restart: "no"
    
    env_file:
      - .env

networks:
  default:
    driver: bridge
