"""Auto migration

Revision ID: a187a11c041d
Revises: b3f9a1d639c1
Create Date: 2025-05-31 16:46:43.783757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a187a11c041d'
down_revision = 'b3f9a1d639c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
