"""Auto migration

Revision ID: b3f9a1d639c1
Revises: 61847d0ac84b
Create Date: 2025-05-30 22:34:12.287754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3f9a1d639c1'
down_revision = '61847d0ac84b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chatrooms', schema=None) as batch_op:
        batch_op.alter_column('participant_ids',
               existing_type=sa.BLOB(),
               type_=sa.JSON(),
               existing_nullable=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('posts_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('author_id')

    with op.batch_alter_table('trade_promises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['creator_id'], ['id'])

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'COMPLETED', name='tradestatus'),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('valuation_opinions', schema=None) as batch_op:
        batch_op.drop_column('content')

    with op.batch_alter_table('valuation_posts', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('thumbnail_image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valuation_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_image_url', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('valuation_opinions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', mysql.TEXT(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('grade',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'COMPLETED', name='tradestatus'),
               type_=mysql.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('trade_promises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('creator_id')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('posts_ibfk_1'), 'users', ['author_id'], ['id'])
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('user_id')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('chatrooms', schema=None) as batch_op:
        batch_op.alter_column('participant_ids',
               existing_type=sa.JSON(),
               type_=sa.BLOB(),
               existing_nullable=False)

    # ### end Alembic commands ###
